
list_kota = ["Aceh",
             "Bali",
             "Bangka Belitung",
             "Banten",
             "Bengkulu",
             "DIY ogyakarta",
             "DKI Jakarta",
             "Gorontalo",
             "Jambi",
             "Jawa Barat",
             "Jawa Tengah",
             "Jawa Timur",
             "Kalimantan Barat",
             "Kalimantan Selatan",
             "Kalimantan Tengah",
             "Kalimantan Timur",
             "Kalimantan Utara",
             "Kepulauan Riau",
             "Lampung",
             "Maluku",
             "Maluku Utara",
             "NusaTenggara Barat",
             "NusaTenggara Timur",
             "Papua",
             "PapuaBarat",
             "Riau",
             "Sulawesi Barat",
             "Sulawesi Selatan",
             "Sulawesi Tengah",
             "Sulawesi Tenggara",
             "Sulawesi Utara",
             "Sumatera Barat",
             "Sumatera Utara"]